In [1]:
###------NYC HISTORIC DATA CRIME : DATA CLEANING-----###

In [2]:
# Data exploration
import pandas as pd
import numpy as np
from data_utility import getCurrentDirectory, readCsvFile

In [3]:
#Get Current Working Directory
listDir = getCurrentDirectory()

In [4]:
## Read CSV
crimes_original = readCsvFile('../Data/NYPD_Complaint_Data_Cleaned.csv')
crimes_original.head()

,CMPLNT_NUM,CMPLNT_FR_DT,CMPLNT_FR_TM,CMPLNT_TO_DT,CMPLNT_TO_TM,RPT_DT,KY_CD,OFNS_DESC,PD_CD,PD_DESC,...,ADDR_PCT_CD,LOC_OF_OCCUR_DESC,PREM_TYP_DESC,PARKS_NM,HADEVELOPT,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,Lat_Lon
0,448788620,2/26/2014,21:20:00,NaN,NaN,2/26/2014,341,PETIT LARCENY,338.0,"LARCENY,PETIT FROM BUILDING,UN",...,6.0,INSIDE,BAR/NIGHT CLUB,NaN,NaN,984440.0,204596.0,40.728254,-73.999316,"(40.728253665, -73.999315931)"
1,937242856,3/30/2014,20:40:00,3/30/2014,20:50:00,3/30/2014,117,DANGEROUS DRUGS,503.0,"CONTROLLED SUBSTANCE,INTENT TO",...,44.0,NaN,RESIDENCE - APT. HOUSE,NaN,NaN,1007702.0,243922.0,40.836162,-73.915250,"(40.836161968, -73.915249813)"
2,967934150,4/16/2014,22:10:00,4/16/2014,22:12:00,4/17/2014,117,DANGEROUS DRUGS,502.0,"CONTROLLED SUBSTANCE,POSSESS.",...,47.0,NaN,STREET,NaN,NaN,1022580.0,265258.0,40.894671,-73.861361,"(40.894670712, -73.86136123)"
3,187201528,4/8/2014,13:45:00,4/8/2014,13:50:00,4/8/2014,117,DANGEROUS DRUGS,521.0,"CONTROLLED SUBSTANCE, SALE 5",...,52.0,NaN,STREET,NaN,NaN,1011583.0,254138.0,40.864191,-73.901183,"(40.864190693, -73.901182887)"
4,695603586,5/17/2014,21:17:00,5/17/2014,21:24:00,5/17/2014,106,FELONY ASSAULT,106.0,"ASSAULT 2,1,PEACE OFFICER",...,40.0,NaN,STREET,NaN,NaN,1009673.0,235504.0,40.813052,-73.908159,"(40.813051503, -73.908158845)"

In [5]:
## Rows, column count
crimes_original.shape

(6039729, 24)

In [6]:
crimes_original.describe(include = [np.number])

,CMPLNT_NUM,KY_CD,PD_CD,ADDR_PCT_CD,X_COORD_CD,Y_COORD_CD,Latitude,Longitude
count,6.039729e+06,6.039729e+06,6.034660e+06,6.039349e+06,5.835875e+06,5.835875e+06,5.835875e+06,5.835875e+06
mean,5.499495e+08,2.944719e+02,4.167404e+02,6.338326e+01,1.004664e+06,2.069691e+05,4.073472e+01,-7.392631e+01
std,2.597827e+08,1.488672e+02,2.181794e+02,3.444687e+01,2.144697e+04,3.048312e+04,8.367193e-02,7.734540e-02
min,1.000002e+08,1.010000e+02,1.010000e+02,1.000000e+00,9.133190e+05,1.208290e+05,4.049806e+01,-7.425508e+01
25%,3.249715e+08,1.170000e+02,2.540000e+02,4.000000e+01,9.917040e+05,1.841890e+05,4.067216e+01,-7.397312e+01
50%,5.499672e+08,3.410000e+02,3.890000e+02,6.300000e+01,1.004298e+06,2.057380e+05,4.073135e+01,-7.392764e+01
75%,7.748499e+08,3.510000e+02,6.370000e+02,9.400000e+01,1.016293e+06,2.351890e+05,4.081219e+01,-7.388423e+01
max,9.999999e+08,8.810000e+02,9.750000e+02,1.230000e+02,1.067298e+06,2.718200e+05,4.091272e+01,-7.370032e+01

In [7]:
crimes_original.describe(include = [np.object])

,CMPLNT_FR_DT,CMPLNT_FR_TM,CMPLNT_TO_DT,CMPLNT_TO_TM,RPT_DT,OFNS_DESC,PD_DESC,CRM_ATPT_CPTD_CD,LAW_CAT_CD,JURIS_DESC,BORO_NM,LOC_OF_OCCUR_DESC,PREM_TYP_DESC,PARKS_NM,HADEVELOPT,Lat_Lon
count,6039729,6039682,4496002,4500082,6039729,6020828,6034660,6039723,6039729,6039729,6039276,4725976,6002919,16605,301576,5835875
unique,4748,1442,4698,1441,4383,70,413,2,3,25,5,5,70,1066,279,114680
top,1/1/2010,12:00:00,10/17/2014,12:00:00,5/29/2007,PETIT LARCENY,ASSAULT 3,COMPLETED,MISDEMEANOR,N.Y. POLICE DEPT,BROOKLYN,INSIDE,STREET,CENTRAL PARK,CASTLE HILL,"(40.750430768, -73.989282176)"
freq,2395,160065,1368,78852,1888,986697,522052,5935699,3436613,5365406,1801587,3019564,1977361,1056,6667,19439

In [8]:
crime_remCol = crimes_original.drop(['CMPLNT_NUM','KY_CD','JURIS_DESC','PD_CD','PARKS_NM','HADEVELOPT','X_COORD_CD','Y_COORD_CD'], axis=1)
print(crime_remCol)

        CMPLNT_FR_DT CMPLNT_FR_TM CMPLNT_TO_DT CMPLNT_TO_TM     RPT_DT  \
0          2/26/2014     21:20:00          NaN          NaN  2/26/2014
1          3/30/2014     20:40:00    3/30/2014     20:50:00  3/30/2014
2          4/16/2014     22:10:00    4/16/2014     22:12:00  4/17/2014
3           4/8/2014     13:45:00     4/8/2014     13:50:00   4/8/2014
4          5/17/2014     21:17:00    5/17/2014     21:24:00  5/17/2014
5          4/26/2014     00:00:00    4/26/2014     00:01:00  4/26/2014
6          4/26/2014     00:00:00    4/26/2014     00:01:00  4/26/2014
7          4/13/2014     21:00:00    4/13/2014     23:35:00  4/13/2014
8          5/15/2014     14:00:00    5/15/2014     16:45:00  5/15/2014
9           5/5/2014     17:15:00          NaN          NaN   5/5/2014
10          4/1/2014     15:00:00     4/1/2014     15:05:00   4/1/2014
11          4/6/2014     14:45:00          NaN          NaN   4/6/2014
12         5/11/2014     02:48:00    5/11/2014     02:55:00  5/11/2014
13         5/11/2014     02:50:00    5/11/2014     02:55:00  5/11/2014
14         4/13/2014     21:30:00          NaN          NaN  4/13/2014
15         3/22/2014     02:52:00    3/22/2014     03:09:00  3/22/2014
16         4/23/2014     16:15:00    4/23/2014     16:27:00  4/23/2014
17         5/19/2014     05:45:00          NaN          NaN  5/19/2014
18         2/11/2014     23:56:00    2/12/2014     00:00:00  2/12/2014
19         3/14/2014     18:59:00    3/14/2014     19:01:00  3/14/2014
20         4/27/2014     10:45:00    4/27/2014     10:50:00  4/27/2014
21          4/1/2014     09:25:00     4/1/2014     09:28:00   4/1/2014
22          5/8/2014     10:00:00     5/9/2014     15:00:00  5/11/2014
23          5/6/2014     14:00:00     5/6/2014     14:05:00   5/6/2014
24          4/4/2014     13:00:00     4/5/2014     01:00:00   4/5/2014
25         3/14/2014     09:12:00    3/14/2014     09:33:00  3/14/2014
26         4/23/2014     15:37:00          NaN          NaN  4/23/2014
27         5/20/2014     19:06:00          NaN          NaN  5/20/2014
28          3/6/2014     23:42:00     3/6/2014     23:42:00   3/7/2014
29          4/2/2014     00:45:00    4/24/2014     00:55:00  4/24/2014
...              ...          ...          ...          ...        ...
6039699    3/30/2006     16:00:00    3/30/2006     17:10:00  3/30/2006
6039700    3/30/2006     19:45:00    3/30/2006     20:01:00  3/30/2006
6039701     4/2/2006     19:00:00     4/3/2006     09:50:00   4/3/2006
6039702    4/23/2006     03:06:00    4/23/2006     03:06:00  4/23/2006
6039703    5/23/2006     02:22:00          NaN          NaN  5/23/2006
6039704    4/11/2006     14:30:00          NaN          NaN  4/11/2006
6039705    4/25/2006     14:07:00          NaN          NaN  4/25/2006
6039706     5/7/2006     12:40:00     5/7/2006     12:43:00   5/7/2006
6039707    5/30/2006     23:00:00    5/30/2006     23:24:00  5/31/2006
6039708     5/4/2006     16:30:00          NaN          NaN   5/4/2006
6039709     4/5/2006     02:30:00          NaN          NaN   4/5/2006
6039710    5/17/2006     20:50:00    5/17/2006     20:56:00  5/17/2006
6039711     5/5/2006     23:40:00          NaN          NaN   5/6/2006
6039712    5/11/2006     16:05:00          NaN          NaN  5/11/2006
6039713    5/11/2006     21:36:00    5/11/2006     21:40:00  5/11/2006
6039714    5/12/2006     02:01:00          NaN          NaN  5/12/2006
6039715    5/15/2006     22:00:00    5/15/2006     22:06:00  5/15/2006
6039716    5/17/2006     03:16:00          NaN          NaN  5/17/2006
6039717    5/18/2006     01:25:00          NaN          NaN  5/18/2006
6039718    4/13/2006     10:50:00    4/13/2006     11:03:00  4/13/2006
6039719     5/3/2006     11:55:00     5/3/2006     12:18:00   5/3/2006
6039720    5/15/2006     18:40:00    5/15/2006     18:50:00  5/15/2006
6039721    3/28/2006     03:16:00    3/28/2006     06:30:00  3/28/2006
6039722    4/18/2006     14:15:00          NaN          NaN  4/18/2006
6039723    4/13/2006     16:20:00    4/13/2006     16:20:00  4/13/2006
6039724    4/19/2006     18:45:00    4/19/2006     19:00:00  4/19/2006
6039725     5/5/2006     13:50:00          NaN          NaN   5/5/2006
6039726    4/15/2006     02:24:00    4/15/2006     02:35:00  4/15/2006
6039727    6/15/2006     13:52:00          NaN          NaN  6/15/2006
6039728    4/14/2006     01:00:00    4/14/2006     01:00:00  4/14/2006

                              OFNS_DESC  \
0                         PETIT LARCENY
1                       DANGEROUS DRUGS
2                       DANGEROUS DRUGS
3                       DANGEROUS DRUGS
4                        FELONY ASSAULT
5                        FELONY ASSAULT
6                        FELONY ASSAULT
7                        FELONY ASSAULT
8                        FELONY ASSAULT
9                        FELONY ASSAULT
10                       FELONY ASSAULT
11                       FELONY ASSAULT
12                       FELONY ASSAULT
13                       FELONY ASSAULT
14                       FELONY ASSAULT
15                       FELONY ASSAULT
16                       FELONY ASSAULT
17                       FELONY ASSAULT
18                              FORGERY
19                        GRAND LARCENY
20                        GRAND LARCENY
21                        GRAND LARCENY
22                        GRAND LARCENY
23       GRAND LARCENY OF MOTOR VEHICLE
24       GRAND LARCENY OF MOTOR VEHICLE
25              MISCELLANEOUS PENAL LAW
26              MISCELLANEOUS PENAL LAW
27              MISCELLANEOUS PENAL LAW
28        POSSESSION OF STOLEN PROPERTY
29                              ROBBERY
...                                 ...
6039699   UNAUTHORIZED USE OF A VEHICLE
6039700   UNAUTHORIZED USE OF A VEHICLE
6039701   UNAUTHORIZED USE OF A VEHICLE
6039702   UNAUTHORIZED USE OF A VEHICLE
6039703   UNAUTHORIZED USE OF A VEHICLE
6039704   UNAUTHORIZED USE OF A VEHICLE
6039705   UNAUTHORIZED USE OF A VEHICLE
6039706   UNAUTHORIZED USE OF A VEHICLE
6039707   UNAUTHORIZED USE OF A VEHICLE
6039708        VEHICLE AND TRAFFIC LAWS
6039709        VEHICLE AND TRAFFIC LAWS
6039710        VEHICLE AND TRAFFIC LAWS
6039711        VEHICLE AND TRAFFIC LAWS
6039712        VEHICLE AND TRAFFIC LAWS
6039713        VEHICLE AND TRAFFIC LAWS
6039714        VEHICLE AND TRAFFIC LAWS
6039715        VEHICLE AND TRAFFIC LAWS
6039716        VEHICLE AND TRAFFIC LAWS
6039717        VEHICLE AND TRAFFIC LAWS
6039718        VEHICLE AND TRAFFIC LAWS
6039719        VEHICLE AND TRAFFIC LAWS
6039720        VEHICLE AND TRAFFIC LAWS
6039721        VEHICLE AND TRAFFIC LAWS
6039722        VEHICLE AND TRAFFIC LAWS
6039723        VEHICLE AND TRAFFIC LAWS
6039724        VEHICLE AND TRAFFIC LAWS
6039725        VEHICLE AND TRAFFIC LAWS
6039726        VEHICLE AND TRAFFIC LAWS
6039727        VEHICLE AND TRAFFIC LAWS
6039728        VEHICLE AND TRAFFIC LAWS

                                                   PD_DESC CRM_ATPT_CPTD_CD  \
0                           LARCENY,PETIT FROM BUILDING,UN              NaN
1                           CONTROLLED SUBSTANCE,INTENT TO        ATTEMPTED
2                            CONTROLLED SUBSTANCE,POSSESS.        ATTEMPTED
3                             CONTROLLED SUBSTANCE, SALE 5        ATTEMPTED
4                                ASSAULT 2,1,PEACE OFFICER        ATTEMPTED
5                                 ASSAULT 2,1,UNCLASSIFIED        ATTEMPTED
6                                 ASSAULT 2,1,UNCLASSIFIED        ATTEMPTED
7                                 ASSAULT 2,1,UNCLASSIFIED        ATTEMPTED
8                                 ASSAULT 2,1,UNCLASSIFIED        ATTEMPTED
9                                 ASSAULT 2,1,UNCLASSIFIED        ATTEMPTED
10                                ASSAULT 2,1,UNCLASSIFIED        ATTEMPTED
11                                ASSAULT 2,1,UNCLASSIFIED        ATTEMPTED
12                               ASSAULT 2,1,PEACE OFFICER        ATTEMPTED
13                                ASSAULT 2,1,UNCLASSIFIED        ATTEMPTED
14                                ASSAULT 2,1,UNCLASSIFIED        ATTEMPTED
15                               ASSAULT 2,1,PEACE OFFICER        ATTEMPTED
16                                ASSAULT 2,1,UNCLASSIFIED        ATTEMPTED
17                               ASSAULT 2,1,PEACE OFFICER        ATTEMPTED
18                          FORGERY,ETC.,UNCLASSIFIED-FELO        ATTEMPTED
19       LARCENY,GRAND FROM PERSON,PERSONAL ELECTRONIC ...        ATTEMPTED
20                          LARCENY,GRAND FROM PERSON,PURS        ATTEMPTED
21                          LARCENY,GRAND FROM PERSON,UNCL        ATTEMPTED
22        LARCENY,GRAND BY FALSE PROMISE-IN PERSON CONTACT        ATTEMPTED
23                                   LARCENY,GRAND OF AUTO        ATTEMPTED
24                                   LARCENY,GRAND OF AUTO        ATTEMPTED
25                                     CRIMINAL CONTEMPT 1        ATTEMPTED
26                           BRIBERY,PUBLIC ADMINISTRATION        ATTEMPTED
27                           BRIBERY,PUBLIC ADMINISTRATION        ATTEMPTED
28                          STOLEN PROPERTY 2,1,POSSESSION        ATTEMPTED
29                      ROBBERY,PERSONAL ELECTRONIC DEVICE        ATTEMPTED
...                                                    ...              ...
6039699                         UNAUTHORIZED USE VEHICLE 3        COMPLETED
6039700                         UNAUTHORIZED USE VEHICLE 3        COMPLETED
6039701                         UNAUTHORIZED USE VEHICLE 3        COMPLETED
6039702                         UNAUTHORIZED USE VEHICLE 3        COMPLETED
6039703                         UNAUTHORIZED USE VEHICLE 3        COMPLETED
6039704                         UNAUTHORIZED USE VEHICLE 3        COMPLETED
6039705                         UNAUTHORIZED USE VEHICLE 3        COMPLETED
6039706                         UNAUTHORIZED USE VEHICLE 3        COMPLETED
6039707                         UNAUTHORIZED USE VEHICLE 3        COMPLETED
6039708                     LEAVING SCENE-ACCIDENT-PERSONA        COMPLETED
6039709                     TRAFFIC,UNCLASSIFIED MISDEMEAN        COMPLETED
6039710                     TRAFFIC,UNCLASSIFIED MISDEMEAN        COMPLETED
6039711                     TRAFFIC,UNCLASSIFIED MISDEMEAN        COMPLETED
6039712                     TRAFFIC,UNCLASSIFIED MISDEMEAN        COMPLETED
6039713                     TRAFFIC,UNCLASSIFIED MISDEMEAN        COMPLETED
6039714                     TRAFFIC,UNCLASSIFIED MISDEMEAN        COMPLETED
6039715                     TRAFFIC,UNCLASSIFIED MISDEMEAN        COMPLETED
6039716                     TRAFFIC,UNCLASSIFIED MISDEMEAN        COMPLETED
6039717                     TRAFFIC,UNCLASSIFIED MISDEMEAN        COMPLETED
6039718                     TRAFFIC,UNCLASSIFIED MISDEMEAN        COMPLETED
6039719                     TRAFFIC,UNCLASSIFIED MISDEMEAN        COMPLETED
6039720                     LEAVING SCENE-ACCIDENT-PERSONA        COMPLETED
6039721                     LEAVING SCENE-ACCIDENT-PERSONA        COMPLETED
6039722                     LEAVING SCENE-ACCIDENT-PERSONA        COMPLETED
6039723                     LEAVING SCENE-ACCIDENT-PERSONA        COMPLETED
6039724                     LEAVING SCENE-ACCIDENT-PERSONA        COMPLETED
6039725                     LEAVING SCENE-ACCIDENT-PERSONA        COMPLETED
6039726                     LEAVING SCENE-ACCIDENT-PERSONA        COMPLETED
6039727                     TRAFFIC,UNCLASSIFIED MISDEMEAN        COMPLETED
6039728                     LEAVING SCENE-ACCIDENT-PERSONA        COMPLETED

          LAW_CAT_CD    BORO_NM  ADDR_PCT_CD LOC_OF_OCCUR_DESC  \
0        MISDEMEANOR  MANHATTAN          6.0            INSIDE
1             FELONY      BRONX         44.0               NaN
2             FELONY      BRONX         47.0               NaN
3             FELONY      BRONX         52.0               NaN
4             FELONY      BRONX         40.0               NaN
5             FELONY      BRONX         41.0               NaN
6             FELONY      BRONX         41.0               NaN
7             FELONY      BRONX         42.0               NaN
8             FELONY      BRONX         42.0               NaN
9             FELONY      BRONX         43.0               NaN
10            FELONY      BRONX         44.0               NaN
11            FELONY      BRONX         44.0               NaN
12            FELONY      BRONX         46.0               NaN
13            FELONY      BRONX         46.0               NaN
14            FELONY      BRONX         47.0               NaN
15            FELONY      BRONX         48.0               NaN
16            FELONY      BRONX         48.0               NaN
17            FELONY      BRONX         52.0               NaN
18            FELONY      BRONX         42.0               NaN
19            FELONY      BRONX         40.0               NaN
20            FELONY      BRONX         41.0               NaN
21            FELONY      BRONX         48.0               NaN
22            FELONY      BRONX         50.0               NaN
23            FELONY      BRONX         44.0               NaN
24            FELONY      BRONX         48.0               NaN
25            FELONY      BRONX         49.0               NaN
26            FELONY      BRONX         40.0               NaN
27            FELONY      BRONX         46.0               NaN
28            FELONY      BRONX         44.0               NaN
29            FELONY      BRONX         44.0               NaN
...              ...        ...          ...               ...
6039699  MISDEMEANOR  MANHATTAN         23.0               NaN
6039700  MISDEMEANOR  MANHATTAN         23.0               NaN
6039701  MISDEMEANOR  MANHATTAN         24.0               NaN
6039702  MISDEMEANOR  MANHATTAN         26.0               NaN
6039703  MISDEMEANOR  MANHATTAN         28.0               NaN
6039704  MISDEMEANOR  MANHATTAN         30.0               NaN
6039705  MISDEMEANOR  MANHATTAN         32.0               NaN
6039706  MISDEMEANOR  MANHATTAN         34.0               NaN
6039707  MISDEMEANOR  MANHATTAN         34.0               NaN
6039708  MISDEMEANOR  MANHATTAN         10.0               NaN
6039709  MISDEMEANOR  MANHATTAN         25.0               NaN
6039710  MISDEMEANOR  MANHATTAN         26.0               NaN
6039711  MISDEMEANOR  MANHATTAN         30.0               NaN
6039712  MISDEMEANOR  MANHATTAN         30.0               NaN
6039713  MISDEMEANOR  MANHATTAN         30.0               NaN
6039714  MISDEMEANOR  MANHATTAN         30.0               NaN
6039715  MISDEMEANOR  MANHATTAN         30.0               NaN
6039716  MISDEMEANOR  MANHATTAN         30.0               NaN
6039717  MISDEMEANOR  MANHATTAN         30.0               NaN
6039718  MISDEMEANOR  MANHATTAN         33.0               NaN
6039719  MISDEMEANOR  MANHATTAN         33.0               NaN
6039720  MISDEMEANOR  MANHATTAN          5.0               NaN
6039721  MISDEMEANOR  MANHATTAN         19.0               NaN
6039722  MISDEMEANOR  MANHATTAN         18.0               NaN
6039723  MISDEMEANOR  MANHATTAN         17.0               NaN
6039724  MISDEMEANOR  MANHATTAN         17.0               NaN
6039725  MISDEMEANOR  MANHATTAN         19.0               NaN
6039726  MISDEMEANOR  MANHATTAN         30.0               NaN
6039727  MISDEMEANOR  MANHATTAN         25.0               NaN
6039728  MISDEMEANOR  MANHATTAN         34.0               NaN

                  PREM_TYP_DESC   Latitude  Longitude  \
0                BAR/NIGHT CLUB  40.728254 -73.999316
1        RESIDENCE - APT. HOUSE  40.836162 -73.915250
2                        STREET  40.894671 -73.861361
3                        STREET  40.864191 -73.901183
4                        STREET  40.813052 -73.908159
5                        STREET  40.814602 -73.885895
6                        STREET  40.814602 -73.885895
7                        STREET  40.824075 -73.908711
8                        STREET  40.832097 -73.889793
9                        STREET  40.826159 -73.877655
10                       STREET  40.825000 -73.916615
11                       STREET  40.830013 -73.918112
12                       STREET  40.860287 -73.894045
13                       STREET  40.860287 -73.894045
14                       STREET  40.873619 -73.848663
15                       STREET  40.851810 -73.889519
16                       STREET  40.858994 -73.893812
17                       STREET  40.864048 -73.892441
18                       STREET  40.829606 -73.902242
19                       STREET  40.815707 -73.916772
20                       STREET  40.826802 -73.891912
21                       STREET  40.856333 -73.883886
22                       STREET  40.878933 -73.904788
23                       STREET  40.828608 -73.921742
24                       STREET  40.842634 -73.878174
25              PUBLIC BUILDING        NaN        NaN
26                       STREET  40.814716 -73.906585
27                       STREET  40.859998 -73.896851
28                       STREET  40.838752 -73.913758
29       OPEN AREAS (OPEN LOTS)  40.835405 -73.920306
...                         ...        ...        ...
6039699                  STREET  40.795549 -73.948095
6039700                  STREET  40.788437 -73.949065
6039701                  STREET  40.799768 -73.966209
6039702                  STREET  40.818025 -73.960423
6039703                  STREET  40.802032 -73.949683
6039704                  STREET  40.826439 -73.950452
6039705                  STREET  40.824140 -73.940973
6039706                  STREET  40.848947 -73.937073
6039707                  STREET  40.863698 -73.917066
6039708                     NaN        NaN        NaN
6039709                     NaN  40.798633 -73.941620
6039710                     NaN  40.816327 -73.957830
6039711                     NaN  40.831479 -73.946770
6039712                     NaN  40.828305 -73.950859
6039713                     NaN  40.822660 -73.951300
6039714                     NaN  40.820014 -73.958875
6039715                     NaN  40.826439 -73.950452
6039716                     NaN  40.826439 -73.950452
6039717                     NaN  40.822266 -73.956157
6039718                     NaN  40.844854 -73.935182
6039719                     NaN  40.837812 -73.942143
6039720                  BRIDGE  40.712158 -74.005358
6039721                  BRIDGE        NaN        NaN
6039722             GAS STATION  40.761561 -73.994071
6039723         HIGHWAY/PARKWAY  40.743220 -73.972257
6039724         HIGHWAY/PARKWAY  40.745778 -73.970423
6039725         HIGHWAY/PARKWAY        NaN        NaN
6039726         HIGHWAY/PARKWAY  40.827288 -73.953689
6039727                   OTHER  40.802453 -73.938832
6039728                   OTHER  40.853725 -73.926802

                               Lat_Lon
0        (40.728253665, -73.999315931)
1        (40.836161968, -73.915249813)
2         (40.894670712, -73.86136123)
3        (40.864190693, -73.901182887)
4        (40.813051503, -73.908158845)
5        (40.814601602, -73.885895461)
6        (40.814601602, -73.885895461)
7         (40.82407474, -73.908710901)
8        (40.832097489, -73.889793458)
9          (40.826159408, -73.8776554)
10       (40.825000207, -73.916615377)
11       (40.830013132, -73.918112312)
12       (40.860286884, -73.894045157)
13       (40.860286884, -73.894045157)
14       (40.873619444, -73.848662781)
15       (40.851809738, -73.889518615)
16       (40.858993916, -73.893812237)
17       (40.864048386, -73.892441179)
18       (40.829605532, -73.902242411)
19        (40.815706699, -73.91677153)
20       (40.826802192, -73.891912412)
21        (40.85633297, -73.883886265)
22       (40.878932741, -73.904787986)
23        (40.828607613, -73.92174192)
24       (40.842633734, -73.878174458)
25                                 NaN
26       (40.814716285, -73.906585036)
27       (40.859998489, -73.896850958)

In [9]:
# Fill CMPLNT_TO_DT NaNs with CMPLNT_FR_DT values.
crime_remCol['CMPLNT_TO_DT'].fillna(crime_remCol['CMPLNT_FR_DT'], axis = 0, inplace = True)
crime_remCol['CMPLNT_FR_DT'].fillna(crime_remCol['CMPLNT_TO_DT'], axis = 0, inplace = True)

# Fill CMPLNT_TO_TM NaNs with CMPLNT_FR_TM values.
crime_remCol['CMPLNT_TO_TM'].fillna(crime_remCol['CMPLNT_FR_TM'], axis = 0, inplace = True)
crime_remCol['CMPLNT_FR_TM'].fillna(crime_remCol['CMPLNT_TO_TM'], axis = 0, inplace = True)

In [10]:
# All NaNs from 'PD_DESC' series are filled with copy of 'OFNS_DESC' values
crime_remCol['OFNS_DESC'] = np.where(crime_remCol['OFNS_DESC'].isnull(), crime_remCol['PD_DESC'], crime_remCol['OFNS_DESC']) # There is pandas equivalent of np.where -> https://stackoverflow.com/questions/38579532/pandas-equivalent-of-np-where
# And vice versa
crime_remCol['PD_DESC'] = np.where(crime_remCol['PD_DESC'].isnull(), crime_remCol['OFNS_DESC'], crime_remCol['PD_DESC'])

In [11]:
#Remove Nan for premises.
prem_typ_desc_copy = crime_remCol['PREM_TYP_DESC'].copy(deep = True)
prem_typ_desc_copy_rand = prem_typ_desc_copy.value_counts(normalize = True).sort_values(ascending = False)

# Fill PREM_TYP_DESC values NaN values with values from locations of other incidents.
crime_remCol['PREM_TYP_DESC'] = crime_remCol['PREM_TYP_DESC'].apply(lambda x: np.random.choice([x for x in crime_remCol.prem_typ_desc],
                          replace = True, p = prem_typ_desc_copy_rand ) if (x == np.nan) else x).astype(str)

In [12]:
#Fill the location of occurance desc with max count
crime_remCol['LOC_OF_OCCUR_DESC'].fillna(value ='INSIDE', axis = 0, inplace = True)

In [13]:
crime_filt1 = crime_remCol.dropna(subset=['CMPLNT_FR_DT', 'CMPLNT_TO_DT'],how = "all")
crime_filt2 = crime_filt1.dropna(subset=['CMPLNT_FR_TM', 'CMPLNT_TO_TM'],how = "all")
crime_filt3 = crime_filt2.dropna(subset=['CRM_ATPT_CPTD_CD'],how = "all")
crime_filt4 = crime_filt3.dropna(subset=['BORO_NM'],how = "all")
crime_filt5 = crime_filt4.dropna(subset=['Latitude','Longitude','Lat_Lon'],how = "all")
#cleanedData = crime_filt5.copy()

In [14]:
crime_filt5.isnull().sum()

#To check the count of rows
#crime_filt5['LOC_OF_OCCUR_DESC'].value_counts(dropna=True)

CMPLNT_FR_DT         0
CMPLNT_FR_TM         0
CMPLNT_TO_DT         0
CMPLNT_TO_TM         0
RPT_DT               0
OFNS_DESC            0
PD_DESC              0
CRM_ATPT_CPTD_CD     0
LAW_CAT_CD           0
BORO_NM              0
ADDR_PCT_CD          0
LOC_OF_OCCUR_DESC    0
PREM_TYP_DESC        0
Latitude             0
Longitude            0
Lat_Lon              0
dtype: int64

In [15]:
data = crime_filt5.iloc[:,0:15].values
cleanedData = pd.DataFrame(data)